language: java

jdk:
  - oraclejdk8

os:
  - linux
  - osx

sudo: false

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

install: /bin/true

script: ./gradlew wrapper --gradle-version 4.6 clean test