site_name: Kotest

# Meta tags (placed in header)
site_description: Kotest test framework for Kotlin.
site_author: Kotest organization
site_url: https://kotest.io

#Copyright (shown at the footer)
copyright: 'Copyright &copy; 2017 Kotest Team'

# Repository (add link to repository on each page)
repo_name: Kotest
repo_url: https://github.com/kotest/kotest

theme:
   name: material
   palette:
      primary: indigo
      accent: deep orange
   logo: 'images/logo.png'
   features:
      - search.highlight
   font:
      text: Nunito Sans

plugins:
   - search

extra:
   social:
      -  icon: fontawesome/brands/slack
         link: https://kotlinlang.slack.com/?redir=%2Farchives%2FCT0G9SD7Z
      -  icon: fontawesome/brands/github
         link: https://github.com/kotest/kotest


nav:
   - "index.md"
   - "styles.md"
   - "assertions.md"
   - "matchers.md"
   - "inspectors.md"
   - "extensions.md"
   - "listeners.md"
   - "property_testing.md"
   - "data_driven_testing.md"
   - "conditional_evaluation.md"
   - "isolation_mode.md"
   - "clues.md"
   - "timeout.md"
   - "project_config.md"
   - "nondeterministic_testing.md"
   - "test_factories.md"
   - "mpp.md"
   - "plugins.md"
   - "blogs.md"
   - "third_party_integrations.md"
