name: release

on:
   workflow_dispatch:
      inputs:
         version:
            description: "The release version"
            required: true

jobs:
   deploy-linux-and-common:
      runs-on: ubuntu-latest

      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v2
            with:
               fetch-depth: 0

         -  name: publish linux and common release
            run: ./gradlew publish
            env:
               RELEASE_VERSION: ${{ github.event.inputs.version }}
               OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
               ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
               ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

   deploy-mac:
      runs-on: macOS-latest
      needs: [ deploy-linux-and-common ]

      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v2
            with:
               fetch-depth: 0

         -  name: publish macosx64 release
            run: ./gradlew publishMacosX64PublicationToDeployRepository
            env:
               OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
               ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
               ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

         -  name: publish tvosX64 release
            run: ./gradlew publishTvosX64PublicationToDeployRepository
            env:
               OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
               ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
               ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

         -  name: publish tvosArm64 release
            run: ./gradlew publishTvosArm64PublicationToDeployRepository
            env:
               OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
               ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
               ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

         -  name: publish watchosX86 release
            run: ./gradlew publishWatchosX86PublicationToDeployRepository
            env:
               OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
               ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
               ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

         -  name: publish watchosArm64 release
            run: ./gradlew publishWatchosArm64PublicationToDeployRepository
            env:
               OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
               ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
               ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

         -  name: publish iosX64 release
            run: ./gradlew publishIosX64PublicationToDeployRepository
            env:
               OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
               ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
               ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

         -  name: publish iosArm64 release
            run: ./gradlew publishIosArm64PublicationToDeployRepository
            env:
               OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
               ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
               ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

         -  name: publish iosArm32 release
            run: ./gradlew publishIosArm32PublicationToDeployRepository
            env:
               OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
               ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
               ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

   deploy-windows:
      runs-on: windows-latest
      needs: [ deploy-mac ]

      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v2
            with:
               fetch-depth: 0

         -  name: deploy to sonatype
            run: ./gradlew publishMingwX64PublicationToDeployRepository
            env:
               RELEASE_VERSION: ${{ github.event.inputs.version }}
               OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
               ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
               ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
