name: release-mac

on:
   workflow_dispatch:
      inputs:
         version:
            description: "The release version"
            required: true
         branch:
            description: "The branch to release from"
            required: true
            default: 'master'
         release-task:
            description: "The gradle release task to run"
            required: true
            type: choice
            options:
               - "publishMacosX64PublicationToDeployRepository"
               - "publishMacosArm64PublicationToDeployRepository"
               - "publishIosX64PublicationToDeployRepository"
               - "publishIosSimulatorArm64PublicationToDeployRepository"
               - "publishIosArm64PublicationToDeployRepository"
               - "publishIosArm32PublicationToDeployRepository"
               - "publishTvosX64PublicationToDeployRepository"
               - "publishTvosArm64PublicationToDeployRepository"
               - "publishWatchosArm32PublicationToDeployRepository"
               - "publishWatchosArm64PublicationToDeployRepository"
               - "publishWatchosX86PublicationToDeployRepository"
               - "publishWatchosX64PublicationToDeployRepository"
               - "publishWatchosSimulatorArm64PublicationToDeployRepository"
               - "publishTvosSimulatorArm64PublicationToDeployRepository"
env:
   RELEASE_VERSION: ${{ github.event.inputs.version }}
   OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
   OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
   ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
   ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxMetaspaceSize=756m -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

permissions:
   contents: read

jobs:
   publish_mac:
      runs-on: macos-11
      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v3
            with:
               fetch-depth: 0
               ref: ${{ github.event.inputs.branch }}

         -  name: Setup JDK
            uses: actions/setup-java@v3
            with:
               distribution: 'adopt'
               java-version: '8'

         -  uses: gradle/gradle-build-action@v2

         -  name: publish
            run: ./gradlew ${{ inputs.release-task }}
